version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: logith
      POSTGRES_PASSWORD: loki
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: flask run
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: postgres://logith:loki@db:5432/flask_db

volumes:
  pgdata:
